### ISSUE TITLE
getiing error

### ISSUE THREAD

**Issue by ghost** [CalinaCristian/source-from-zeit-deployment#16]
✖ Loading source files tree
TypeError: Cannot destructure property 'name' of 'undefined' as it is undefined.
    at flattenTree (file:///c:/Users/Rohit/Downloads/xrp/dash/get-vercel-source-code/index.js:108:24)
    at getDeploymentSource (file:///c:/Users/Rohit/Downloads/xrp/dash/get-vercel-source-code/index.js:70:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async oraPromise (file:///c:/Users/Rohit/Downloads/xrp/dash/get-vercel-source-code/node_modules/ora/index.js:412:18)
    at async main (file:///c:/Users/Rohit/Downloads/xrp/dash/get-vercel-source-code/index.js:41:20)
    at async file:///c:/Users/Rohit/Downloads/xrp/dash/get-vercel-source-code/index.js:28:5

**Comment by CalinaCristian** [comment]
fixed by @AliAryanTech [here](https://github.com/CalinaCristian/source-from-vercel-deployment/issues/20#issuecomment-1823566184)
